# Generated by Django 5.1.4 on 2024-12-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('emailid', models.EmailField(max_length=264)),
                ('contact', models.IntegerField(max_length=264)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
