# Generated by Django 5.1.4 on 2024-12-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_signup_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='contact',
        ),
    ]
