# Generated by Django 5.1.4 on 2024-12-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_remove_signup_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='messages',
            field=models.CharField(default='null', max_length=264),
        ),
        migrations.AddField(
            model_name='signup',
            name='subject',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
