# Generated by Django 5.1.4 on 2024-12-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_hm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hm',
            old_name='contact',
            new_name='contactt',
        ),
    ]
